const express = require('express');
const router = express.Router();
const { register, login, verifyOtp, resendOtp, getOtpStatus, getProfile, updateProfile } = require('../controllers/authController');
const { protect } = require('../middleware/auth');
router.post('/register', register);
router.post('/login', login);
router.post('/otp/status', getOtpStatus);
router.post('/otp/resend', resendOtp);
router.post('/otp/verify', verifyOtp);
router.get('/me', protect, getProfile);
router.put('/me', protect, updateProfile);
module.exports = router;